/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  // tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  apiSidebar: [
    {
      type: 'category',
      label: '@perseid/dev-kit',
      items: [
        'api/dev-kit/config',
        'api/dev-kit/commands',
      ],
    },
    {
      type: 'category',
      label: '@perseid/core',
      items: [
        'api/core/helpers',
        'api/core/Id',
        'api/core/Logger',
        'api/core/I18n',
        'api/core/Model',
      ],
    },
    {
      type: 'category',
      label: '@perseid/server',
      items: [
        'api/server/Model',
        'api/server/Errors',
        'api/server/Logger',
        'api/server/Engine',
        'api/server/Profiler',
        'api/server/Controller',
        'api/server/CacheClient',
        'api/server/UsersEngine',
        'api/server/EmailClient',
        'api/server/BucketClient',
        'api/server/DatabaseClient',
        'api/server/FastifyController',
      ],
    },
    {
      type: 'category',
      label: '@perseid/jobs',
      items: [
        'api/jobs/JobScheduler',
        'api/jobs/DatabaseClient',
      ],
    },
    {
      type: 'category',
      label: '@perseid/design',
      items: ['api/design/intro'],
    },
    {
      type: 'category',
      label: '@perseid/form',
      items: ['api/form/intro'],
    },
    {
      type: 'category',
      label: '@perseid/client',
      items: ['api/client/intro'],
    },
  ],
};

export default sidebars;
