/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  // tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  learnSidebar: [
    {
      type: 'category',
      label: 'Quick start',
      collapsible: false,
      items: [
        {
          type: 'doc',
          id: "learn/intro",
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: "learn/step-1",
          label: 'It all starts with a data model',
        },
        {
          type: 'doc',
          id: "learn/step-2",
          label: 'Setting up the back-end',
        },
        {
          type: 'doc',
          id: "learn/step-3",
          label: 'Setting up the front-end',
        },
        {
          type: 'doc',
          id: "learn/step-4",
          label: 'Bonus: setting up a job scheduler',
        },
        {
          type: 'doc',
          id: "learn/step-5",
          label: 'Customizing your app',
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: '@perseid/dev-kit',
      items: [
        'api/dev-kit/config',
        'api/dev-kit/commands',
      ],
    },
    {
      type: 'category',
      label: '@perseid/core',
      items: [
        'api/core/helpers',
        'api/core/Id',
        'api/core/Logger',
        'api/core/I18n',
        'api/core/Model',
      ],
    },
    {
      type: 'category',
      label: '@perseid/server',
      items: [
        'api/server/Model',
        'api/server/Errors',
        'api/server/Logger',
        'api/server/Engine',
        'api/server/Profiler',
        'api/server/Controller',
        'api/server/CacheClient',
        'api/server/UsersEngine',
        'api/server/EmailClient',
        'api/server/BucketClient',
        'api/server/DatabaseClient',
        'api/server/FastifyController',
      ],
    },
    {
      type: 'category',
      label: '@perseid/jobs',
      items: [
        'api/jobs/JobScheduler',
        'api/jobs/DatabaseClient',
      ],
    },
    {
      type: 'category',
      label: '@perseid/store',
      items: [
        {
          type: 'doc',
          id: "api/store/Store",
          label: 'Store',
        },
        {
          type: 'doc',
          id: "api/store/React",
          label: 'React connector',
        },
        {
          type: 'doc',
          id: "api/store/Vue",
          label: 'Vue connector',
        },
        {
          type: 'doc',
          id: "api/store/Svelte",
          label: 'Svelte connector',
        },
        {
          type: 'doc',
          id: "api/store/Router",
          label: 'Router extension',
        },
      ],
    },
    {
      type: 'category',
      label: '@perseid/ui',
      items: [
        {
          type: 'doc',
          id: "api/ui/Helpers",
          label: 'Helpers',
        },
        {
          type: 'doc',
          id: "api/ui/React",
          label: 'React',
        },
        {
          type: 'doc',
          id: "api/ui/Svelte",
          label: 'Svelte',
        },
        {
          type: 'doc',
          id: "api/ui/Vue",
          label: 'Vue',
        },
      ],
    },
    {
      type: 'category',
      label: '@perseid/form',
      items: [
        {
          type: 'doc',
          id: "api/form/Engine",
          label: 'Engine',
        },
        {
          type: 'doc',
          id: "api/form/Plugins",
          label: 'Plugins',
        },
        {
          type: 'doc',
          id: "api/form/React",
          label: 'React',
        },
        {
          type: 'doc',
          id: "api/form/Svelte",
          label: 'Svelte',
        },
        {
          type: 'doc',
          id: "api/form/Vue",
          label: 'Vue',
        },
      ],
    },
    {
      type: 'category',
      label: '@perseid/client',
      items: [
        {
          type: 'doc',
          id: "api/client/ApiClient",
          label: 'ApiClient',
        },
        {
          type: 'doc',
          id: "api/client/Logger",
          label: 'Logger',
        },
        {
          type: 'doc',
          id: "api/client/Model",
          label: 'Model',
        },
        {
          type: 'doc',
          id: "api/client/FormBuilder",
          label: 'FormBuilder',
        },
        {
          type: 'doc',
          id: "api/client/Store",
          label: 'Store',
        },
        {
          type: 'doc',
          id: "api/client/React",
          label: 'React',
        },
      ],
    },
  ],
};

export default sidebars;
